<?php

/**
 * Block Metadata Registry
 *
 * This file contains all block metadata as PHP arrays.
 * It replaces the need to read individual block.json files.
 * 
 * This file is auto-generated by: npm run build:blocks-php
 * Do not edit this file manually. Edit block.json files instead.
 *
 * @package ShapedPlugin\WooProductSliderPro\Blocks
 */

use function PHPSTORM_META\type;

defined('ABSPATH') || exit;

return array(
	'add-to-cart' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/add-to-cart',
		'title' => 'Add to Cart Button',
		'description' => 'Display a call to action button which either adds the product to the cart, or links to the product page.',
		'category' => 'smart-store-pro-element',
		'keywords' => array(
			'WooCommerce',
			'product',
			'cart'
		),
		'usesContext' => array(
			'query',
			'queryId',
			'postId'
		),
		'textdomain' => 'woo-product-slider-pro',
		'attributes' => array(
			'productId' => array(
				'type' => 'number',
				'default' => 0
			),
			'textAlign' => array(
				'type' => 'string',
				'default' => ''
			),
			'width' => array(
				'type' => 'number'
			),
			'isDescendentOfSingleProductBlock' => array(
				'type' => 'boolean',
				'default' => false
			),
			'isDescendentOfQueryLoop' => array(
				'type' => 'boolean',
				'default' => false
			)
		),
		'supports' => array(
			'align' => array(
				'wide',
				'full'
			),
			'color' => array(
				'text' => true,
				'background' => true,
				'link' => false,
				'__experimentalSkipSerialization' => true
			),
			'interactivity' => true,
			'html' => false,
			'typography' => array(
				'fontSize' => true,
				'lineHeight' => true,
				'__experimentalFontWeight' => true,
				'__experimentalFontFamily' => true,
				'__experimentalFontStyle' => true,
				'__experimentalTextTransform' => true,
				'__experimentalTextDecoration' => true,
				'__experimentalLetterSpacing' => true,
				'__experimentalDefaultControls' => array(
					'fontSize' => true
				)
			),
			'__experimentalBorder' => array(
				'radius' => true,
				'__experimentalSkipSerialization' => true
			),
			'spacing' => array(
				'margin' => true,
				'padding' => true,
				'__experimentalSkipSerialization' => true
			),
			'email' => true,
			'__experimentalSelector' => '.wp-block-button.spssp-block-components-product-button .spssp-block-components-product-button__button'
		),
		'ancestor' => array(
			'smart-store-pro/all-products',
			'smart-store-pro/single-product',
			'core/post-template',
			'smart-store-pro/product-template'
		),
		'styles' => array(
			array(
				'name' => 'fill',
				'label' => 'Fill',
				'isDefault' => true
			),
			array(
				'name' => 'outline',
				'label' => 'Outline'
			)
		)
	),

	'container' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/container',
		'title' => 'Container',
		'category' => 'smart-store-pro-smart',
		'keywords' => array(
			'container',
			'wrapper',
			'layout'
		),
		'description' => 'A flexible container block.',
		'textdomain' => 'woo-product-slider-pro',
		'supports' => array(
			'align' => array(
				'wide',
				'full'
			),
			'html' => false,
			'multiple' => true,
			'reusable' => true,
			'innerBlocks' => true,
			'spacing' => array(
				'padding' => true,
				'margin' => true
			)
		)
	),

	'product-carousel' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/product-carousel',
		'title' => 'Product Carousel',
		'description' => 'Display a collection of products from your store in a carousel/slider layout.',
		'category' => 'smart-store-pro-showcase',
		'keywords' => array(
			'WooCommerce',
			'Products',
			'Carousel',
			'Slider',
			'all products',
			'by category',
			'by tag'
		),
		'textdomain' => 'woo-product-slider-pro',
		'attributes' => array(
			'queryId' => array(
				'type' => 'number'
			),
			'query' => array(
				'type' => 'object',
				'properties' => array(
					'perPage' => array(
						'type' => 'number',
						'default' => 6
					),
					'pages' => array(
						'type' => 'number',
						'default' => 0
					),
					'offset' => array(
						'type' => 'number',
						'default' => 0
					),
					'postType' => array(
						'type' => 'string',
						'default' => 'product'
					),
					'order' => array(
						'type' => 'string',
						'default' => 'asc'
					),
					'orderBy' => array(
						'type' => 'string',
						'default' => 'title'
					),
					'search' => array(
						'type' => 'string',
						'default' => ''
					),
					'exclude' => array(
						'type' => 'array',
						'default' => array()
					),
					'inherit' => array(
						'type' => 'boolean',
						'default' => false
					),
					'taxQuery' => array(
						'type' => 'object'
					),
					'featured' => array(
						'type' => 'boolean',
						'default' => false
					),
					'woocommerceOnSale' => array(
						'type' => 'boolean',
						'default' => false
					),
					'woocommerceStockStatus' => array(
						'type' => 'array',
						'default' => array(
							'instock',
							'outofstock',
							'onbackorder'
						)
					),
					'woocommerceHandPickedProducts' => array(
						'type' => 'array',
						'default' => array()
					),
					'priceRange' => array(
						'type' => 'object',
						'properties' => array(
							'min' => array(
								'type' => 'number'
							),
							'max' => array(
								'type' => 'number'
							)
						)
					),
					'filterable' => array(
						'type' => 'boolean',
						'default' => false
					),
					'filterByCategories' => array(
						'type' => 'array',
						'default' => array()
					),
					'filterByTags' => array(
						'type' => 'array',
						'default' => array()
					),
					'filterByBrands' => array(
						'type' => 'array',
						'default' => array()
					),
					'filterByAttributes' => array(
						'type' => 'array',
						'default' => array()
					),
					'filterBySKUs' => array(
						'type' => 'array',
						'default' => array()
					),
					'filterProductBy' => array(
						'type' => 'string',
						'default' => 'latest'
					),
					'filterByDate' => array(
						'type' => 'string',
						'default' => 'all'
					),
					'productType' => array(
						'type' => 'array',
						'default' => array()
					),
					'includeProducts' => array(
						'type' => 'array',
						'default' => array()
					),
					'excludeProducts' => array(
						'type' => 'array',
						'default' => array()
					),
					'excludeCategories' => array(
						'type' => 'array',
						'default' => array()
					),
					'excludeAuthor' => array(
						'type' => 'array',
						'default' => array()
					),
					'outOfStockProducts' => array(
						'type' => 'boolean',
						'default' => false
					),
					'hideOnSaleProducts' => array(
						'type' => 'boolean',
						'default' => false
					),
					'hideFreeProducts' => array(
						'type' => 'boolean',
						'default' => false
					),
					'productsWithoutThumb' => array(
						'type' => 'boolean',
						'default' => false
					),
					'showHiddenProducts' => array(
						'type' => 'boolean',
						'default' => false
					),
					'noResultFoundLabel' => array(
						'type' => 'string',
						'default' => 'No Products Found'
					)
				)
			),
			'tagName' => array(
				'type' => 'string'
			),
			'displayLayout' => array(
				'type' => 'object',
				'properties' => array(
					'type' => array(
						'type' => 'string',
						'enum' => array(
							'carousel'
						)
					),
					'columns' => array(
						'type' => array(
							'number',
							'object'
						)
					),
					'shrinkColumns' => array(
						'type' => 'boolean'
					)
				)
			),
			'dimensions' => array(
				'type' => 'object'
			),
			'convertedFromProducts' => array(
				'type' => 'boolean',
				'default' => false
			),
			'collection' => array(
				'type' => 'string'
			),
			'hideControls' => array(
				'default' => array(),
				'type' => 'array'
			),
			'queryContextIncludes' => array(
				'type' => 'array'
			),
			'forcePageReload' => array(
				'type' => 'boolean',
				'default' => false
			),
			'__privatePreviewState' => array(
				'type' => 'object'
			),
			'autoplay' => array(
				'type' => 'boolean',
				'default' => false
			),
			'autoplaySpeed' => array(
				'type' => array(
					'number',
					'object'
				),
				'default' => array(
					'value' => 3000,
					'unit' => 'ms'
				)
			),
			'arrows' => array(
				'type' => 'boolean',
				'default' => true
			),
			'dots' => array(
				'type' => 'boolean',
				'default' => false
			),
			'infinite' => array(
				'type' => 'boolean',
				'default' => true
			),
			'slidesToShow' => array(
				'type' => 'number',
				'default' => 4
			),
			'slidesToScroll' => array(
				'type' => 'number',
				'default' => 1
			),
			'carouselStyle' => array(
				'type' => 'string',
				'default' => 'standard'
			),
			'carouselGap' => array(
				'type' => array(
					'number',
					'object'
				),
				'default' => 24
			),
			'pauseOnHover' => array(
				'type' => 'boolean',
				'default' => false
			),
			'animationEffect' => array(
				'type' => 'string',
				'default' => 'slide'
			),
			'adaptiveHeight' => array(
				'type' => 'boolean',
				'default' => false
			),
			'keyboardNavigation' => array(
				'type' => 'boolean',
				'default' => false
			),
			'mousewheelControl' => array(
				'type' => 'boolean',
				'default' => false
			),
			'freeScrollMode' => array(
				'type' => 'boolean',
				'default' => false
			),
			'carouselDirection' => array(
				'type' => 'string',
				'default' => 'right_to_left'
			),
			'showPartialView' => array(
				'type' => 'boolean',
				'default' => false
			),
			'equalHeight' => array(
				'type' => 'boolean',
				'default' => false
			),
			'carouselSpeed' => array(
				'type' => array(
					'number',
					'object'
				),
				'default' => array(
					'value' => 600,
					'unit' => 'ms'
				)
			),
			'uniqueId' => array(
				'type' => 'string'
			),
			'paginate' => array(
				'type' => 'boolean',
				'default' => false
			),
			'page' => array(
				'type' => 'number',
				'default' => 1
			),
			'motionEffects' => array(
				'type' => 'object'
			),
			'advancedOptions' => array(
				'type' => 'object',
				'properties' => array(
					'hideOnDesktop' => array(
						'type' => 'boolean',
						'default' => false
					),
					'hideOnTablet' => array(
						'type' => 'boolean',
						'default' => false
					),
					'hideOnMobile' => array(
						'type' => 'boolean',
						'default' => false
					),
					'enablePreloader' => array(
						'type' => 'boolean',
						'default' => false
					),
					'customCSSClass' => array(
						'type' => 'string',
						'default' => ''
					),
					'customCSSID' => array(
						'type' => 'string',
						'default' => ''
					),
					'ariaLabel' => array(
						'type' => 'string',
						'default' => ''
					),
					'skipToContent' => array(
						'type' => 'boolean',
						'default' => false
					)
				)
			),
			'advancedStyle' => array(
				'type' => 'object',
				'properties' => array(
					'background' => array(
						'type' => 'object'
					),
					'border' => array(
						'type' => 'object'
					),
					'borderWidth' => array(
						'type' => 'object'
					),
					'borderRadius' => array(
						'type' => 'object'
					),
					'boxShadow' => array(
						'type' => 'object'
					),
					'padding' => array(
						'type' => 'object'
					),
					'margin' => array(
						'type' => 'object'
					)
				)
			)
		),
		'providesContext' => array(
			'queryId' => 'queryId',
			'query' => 'query',
			'displayLayout' => 'displayLayout',
			'dimensions' => 'dimensions',
			'queryContextIncludes' => 'queryContextIncludes',
			'collection' => 'collection',
			'__privateProductCollectionPreviewState' => '__privatePreviewState'
		),
		'usesContext' => array(
			'templateSlug',
			'postId'
		),
		'style' => 'file:../../../src/Frontend/assets/css/swiper.min.css',
		'editorStyle' => 'file:../../../src/Frontend/assets/css/swiper.min.css',
		'supports' => array(
			'align' => array(
				'wide',
				'full'
			),
			'anchor' => true,
			'html' => false,
			'__experimentalLayout' => true,
			'interactivity' => true,
			'email' => true
		),
		'editorScript' => array(
			'spssp-swiper',
			'file:../../../assets/js/frontend.js'
		),
		'viewScript' => array(
			'spssp-swiper',
			'file:../../../assets/js/frontend.js'
		)
	),

	'product-category' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/product-category',
		'title' => 'Product Category',
		'description' => 'Display product categories.',
		'category' => 'smart-store-pro-element',
		'attributes' => array(
			'productId' => array(
				'type' => 'number',
				'default' => 0
			),
			'prefix' => array(
				'type' => 'string',
				'default' => ''
			),
			'suffix' => array(
				'type' => 'string',
				'default' => ''
			)
		),
		'usesContext' => array(
			'query',
			'queryId',
			'postId'
		),
		'ancestor' => array(
			'smart-store-pro/product-meta',
			'smart-store-pro/all-products',
			'smart-store-pro/single-product',
			'smart-store-pro/product-template',
			'core/post-template'
		),
		'supports' => array(
			'html' => false,
			'interactivity' => array(
				'clientNavigation' => true
			),
			'color' => array(
				'text' => true,
				'background' => true
			),
			'typography' => array(
				'fontSize' => true,
				'lineHeight' => true,
				'__experimentalFontWeight' => true,
				'__experimentalFontFamily' => true,
				'__experimentalFontStyle' => true,
				'__experimentalTextTransform' => true,
				'__experimentalTextDecoration' => true,
				'__experimentalLetterSpacing' => true
			),
			'spacing' => array(
				'margin' => true,
				'padding' => true
			)
		),
		'keywords' => array(
			'WooCommerce',
			'product',
			'category'
		),
		'textdomain' => 'woo-product-slider-pro'
	),

	'product-grid' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/product-grid',
		'title' => 'Product Grid',
		'description' => 'Display a collection of products from your store in a grid layout.',
		'category' => 'smart-store-pro-showcase',
		'keywords' => array(
			'WooCommerce',
			'Products',
			'Grid',
			'all products',
			'by category',
			'by tag'
		),
		'textdomain' => 'woo-product-slider-pro',
		'attributes' => array(
			'queryId' => array(
				'type' => 'number'
			),
			'query' => array(
				'type' => 'object',
				'properties' => array(
					'perPage' => array(
						'type' => 'number',
						'default' => 8
					),
					'pages' => array(
						'type' => 'number',
						'default' => 0
					),
					'offset' => array(
						'type' => 'number',
						'default' => 0
					),
					'postType' => array(
						'type' => 'string',
						'default' => 'product'
					),
					'order' => array(
						'type' => 'string',
						'default' => 'asc'
					),
					'orderBy' => array(
						'type' => 'string',
						'default' => 'title'
					),
					'search' => array(
						'type' => 'string',
						'default' => ''
					),
					'exclude' => array(
						'type' => 'array',
						'default' => array()
					),
					'inherit' => array(
						'type' => 'boolean',
						'default' => false
					),
					'taxQuery' => array(
						'type' => 'object'
					),
					'featured' => array(
						'type' => 'boolean',
						'default' => false
					),
					'woocommerceOnSale' => array(
						'type' => 'boolean',
						'default' => false
					),
					'woocommerceStockStatus' => array(
						'type' => 'array',
						'default' => array(
							'instock',
							'outofstock',
							'onbackorder'
						)
					),
					'woocommerceHandPickedProducts' => array(
						'type' => 'array',
						'default' => array()
					),
					'priceRange' => array(
						'type' => 'object',
						'properties' => array(
							'min' => array(
								'type' => 'number'
							),
							'max' => array(
								'type' => 'number'
							)
						)
					),
					'filterable' => array(
						'type' => 'boolean',
						'default' => false
					),
					'filterByCategories' => array(
						'type' => 'array',
						'default' => array()
					),
					'filterByTags' => array(
						'type' => 'array',
						'default' => array()
					),
					'filterByBrands' => array(
						'type' => 'array',
						'default' => array()
					),
					'filterByAttributes' => array(
						'type' => 'array',
						'default' => array()
					),
					'filterBySKUs' => array(
						'type' => 'array',
						'default' => array()
					),
					'productType' => array(
						'type' => 'array',
						'default' => array()
					),
					'includeProducts' => array(
						'type' => 'array',
						'default' => array()
					),
					'excludeProducts' => array(
						'type' => 'array',
						'default' => array()
					),
					'excludeCategories' => array(
						'type' => 'array',
						'default' => array()
					),
					'excludeAuthor' => array(
						'type' => 'array',
						'default' => array()
					),
					'outOfStockProducts' => array(
						'type' => 'boolean',
						'default' => false
					),
					'hideOnSaleProducts' => array(
						'type' => 'boolean',
						'default' => false
					),
					'hideFreeProducts' => array(
						'type' => 'boolean',
						'default' => false
					),
					'productsWithoutThumb' => array(
						'type' => 'boolean',
						'default' => false
					),
					'showHiddenProducts' => array(
						'type' => 'boolean',
						'default' => false
					),
					'filterProductBy' => array(
						'type' => 'string',
						'default' => 'latest'
					),
					'filterByDate' => array(
						'type' => 'string',
						'default' => 'all'
					),
					'noResultFoundLabel' => array(
						'type' => 'string',
						'default' => 'No Products Found'
					)
				)
			),
			'tagName' => array(
				'type' => 'string'
			),
			'displayLayout' => array(
				'type' => 'object',
				'properties' => array(
					'type' => array(
						'type' => 'string',
						'enum' => array(
							'flex',
							'list'
						)
					),
					'columns' => array(
						'type' => 'number'
					),
					'shrinkColumns' => array(
						'type' => 'boolean'
					)
				)
			),
			'dimensions' => array(
				'type' => 'object'
			),
			'convertedFromProducts' => array(
				'type' => 'boolean',
				'default' => false
			),
			'collection' => array(
				'type' => 'string'
			),
			'hideControls' => array(
				'default' => array(),
				'type' => 'array'
			),
			'queryContextIncludes' => array(
				'type' => 'array'
			),
			'forcePageReload' => array(
				'type' => 'boolean',
				'default' => false
			),
			'paginate' => array(
				'type' => 'boolean',
				'default' => false
			),
			'page' => array(
				'type' => 'number',
				'default' => 1
			),
			'gridStyle' => array(
				'type' => 'object',
				'properties' => array(
					'columns' => array(
						'type' => 'object'
					),
					'horizontalGap' => array(
						'type' => 'object'
					),
					'verticalGap' => array(
						'type' => 'object'
					),
					'contentAlignment' => array(
						'type' => 'string'
					),
					'linkColumnGap' => array(
						'type' => 'boolean',
						'default' => false
					),
					'linkRowGap' => array(
						'type' => 'boolean',
						'default' => false
					)
				)
			),
			'smartPagination' => array(
				'type' => 'boolean',
				'default' => true
			),
			'motionEffects' => array(
				'type' => 'object'
			),
			'advancedOptions' => array(
				'type' => 'object',
				'properties' => array(
					'hideOnDesktop' => array(
						'type' => 'boolean',
						'default' => false
					),
					'hideOnTablet' => array(
						'type' => 'boolean',
						'default' => false
					),
					'hideOnMobile' => array(
						'type' => 'boolean',
						'default' => false
					),
					'enablePreloader' => array(
						'type' => 'boolean',
						'default' => false
					),
					'customCSSClass' => array(
						'type' => 'string',
						'default' => ''
					),
					'customCSSID' => array(
						'type' => 'string',
						'default' => ''
					),
					'ariaLabel' => array(
						'type' => 'string',
						'default' => ''
					),
					'skipToContent' => array(
						'type' => 'boolean',
						'default' => false
					)
				)
			),
			'advancedStyle' => array(
				'type' => 'object',
				'properties' => array(
					'background' => array(
						'type' => 'object'
					),
					'border' => array(
						'type' => 'object'
					),
					'borderWidth' => array(
						'type' => 'object'
					),
					'borderRadius' => array(
						'type' => 'object'
					),
					'boxShadow' => array(
						'type' => 'object'
					),
					'padding' => array(
						'type' => 'object'
					),
					'margin' => array(
						'type' => 'object'
					)
				)
			),
			'__privatePreviewState' => array(
				'type' => 'object'
			)
		),
		'providesContext' => array(
			'queryId' => 'queryId',
			'query' => 'query',
			'displayLayout' => 'displayLayout',
			'dimensions' => 'dimensions',
			'queryContextIncludes' => 'queryContextIncludes',
			'collection' => 'collection',
			'__privateProductCollectionPreviewState' => '__privatePreviewState'
		),
		'usesContext' => array(
			'templateSlug',
			'postId'
		),
		'supports' => array(
			'align' => array(
				'wide',
				'full'
			),
			'anchor' => true,
			'html' => false,
			'__experimentalLayout' => true,
			'interactivity' => true,
			'email' => true
		),
		'style' => 'file:./style.css',
		'editorStyle' => 'file:./editor.css'
	),

	'product-image' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/product-image',
		'title' => 'Product Image',
		'description' => 'Display the main product image.',
		'category' => 'smart-store-pro-element',
		'attributes' => array(
			'showProductLink' => array(
				'type' => 'boolean',
				'default' => true
			),
			'showSaleBadge' => array(
				'type' => 'boolean',
				'default' => true
			),
			'saleBadgeAlign' => array(
				'type' => 'string',
				'default' => 'right'
			),
			'imageSizing' => array(
				'type' => 'string',
				'default' => 'single'
			),
			'productId' => array(
				'type' => 'number',
				'default' => 0
			),
			'isDescendentOfQueryLoop' => array(
				'type' => 'boolean',
				'default' => false
			),
			'isDescendentOfSingleProductBlock' => array(
				'type' => 'boolean',
				'default' => false
			),
			'width' => array(
				'type' => 'string'
			),
			'height' => array(
				'type' => 'string'
			),
			'scale' => array(
				'type' => 'string',
				'default' => 'cover'
			),
			'aspectRatio' => array(
				'type' => 'string'
			)
		),
		'supports' => array(
			'interactivity' => array(
				'clientNavigation' => true
			),
			'html' => false,
			'__experimentalBorder' => array(
				'radius' => true,
				'__experimentalSkipSerialization' => true
			),
			'typography' => array(
				'fontSize' => true,
				'__experimentalSkipSerialization' => true
			),
			'spacing' => array(
				'margin' => true,
				'padding' => true
			),
			'dimensions' => array(
				'aspectRatio' => true,
				'__experimentalSkipSerialization' => true
			),
			'email' => true,
			'__experimentalSelector' => '.spssp-block-components-product-image'
		),
		'ancestor' => array(
			'smart-store-pro/all-products',
			'smart-store-pro/single-product',
			'smart-store-pro/product-template',
			'core/post-template'
		),
		'usesContext' => array(
			'imageId',
			'postId',
			'query',
			'queryId'
		),
		'keywords' => array(
			'WooCommerce',
			'product',
			'image'
		),
		'textdomain' => 'woo-product-slider-pro'
	),

	'product-meta' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/product-meta',
		'title' => 'Product Meta',
		'icon' => 'product',
		'description' => 'Display a product\'s SKU, categories, tags, and more.',
		'category' => 'smart-store-pro-element',
		'supports' => array(
			'interactivity' => array(
				'clientNavigation' => true
			),
			'align' => true,
			'reusable' => false
		),
		'keywords' => array(
			'WooCommerce',
			'product',
			'meta'
		),
		'usesContext' => array(
			'postId',
			'postType',
			'queryId'
		),
		'textdomain' => 'woo-product-slider-pro'
	),

	'product-price' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/product-price',
		'version' => '1.0.0',
		'title' => 'Product Price',
		'category' => 'smart-store-pro-element',
		'keywords' => array(
			'product',
			'price',
			'woocommerce'
		),
		'description' => 'Display the price of a product.',
		'textdomain' => 'woo-product-slider-pro',
		'usesContext' => array(
			'query',
			'queryId',
			'postId'
		),
		'supports' => array(
			'html' => false,
			'interactivity' => true,
			'color' => array(
				'text' => true,
				'background' => true,
				'link' => false
			),
			'typography' => array(
				'fontSize' => true,
				'lineHeight' => true,
				'__experimentalFontFamily' => true,
				'__experimentalFontWeight' => true,
				'__experimentalFontStyle' => true,
				'__experimentalLetterSpacing' => true
			),
			'__experimentalSelector' => '.spssp-block-components-product-price',
			'spacing' => array(
				'margin' => true,
				'padding' => true
			)
		),
		'attributes' => array(
			'productId' => array(
				'type' => 'number',
				'default' => 0
			),
			'isDescendentOfQueryLoop' => array(
				'type' => 'boolean',
				'default' => false
			),
			'textAlign' => array(
				'type' => 'string',
				'default' => 'left'
			),
			'isDescendentOfSingleProductTemplate' => array(
				'type' => 'boolean',
				'default' => false
			),
			'isDescendentOfSingleProductBlock' => array(
				'type' => 'boolean',
				'default' => false
			)
		)
	),

	'product-quantity' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/product-quantity',
		'title' => 'Product Quantity',
		'description' => 'Display product quantity selector.',
		'category' => 'smart-store-pro-element',
		'attributes' => array(
			'productId' => array(
				'type' => 'number',
				'default' => 0
			),
			'min' => array(
				'type' => 'number',
				'default' => 1
			),
			'max' => array(
				'type' => 'number',
				'default' => 99
			),
			'step' => array(
				'type' => 'number',
				'default' => 1
			)
		),
		'usesContext' => array(
			'query',
			'queryId',
			'postId'
		),
		'ancestor' => array(
			'smart-store-pro/all-products',
			'smart-store-pro/single-product',
			'smart-store-pro/product-template',
			'core/post-template'
		),
		'supports' => array(
			'html' => false,
			'interactivity' => true,
			'color' => array(
				'text' => true,
				'background' => true
			),
			'typography' => array(
				'fontSize' => true,
				'lineHeight' => true
			),
			'spacing' => array(
				'margin' => true,
				'padding' => true
			)
		),
		'keywords' => array(
			'WooCommerce',
			'product',
			'quantity'
		),
		'textdomain' => 'woo-product-slider-pro'
	),

	'product-rating' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/product-rating',
		'icon' => 'info',
		'title' => 'Product Rating',
		'description' => 'Display the average rating of a product.',
		'category' => 'smart-store-pro-element',
		'attributes' => array(
			'productId' => array(
				'type' => 'number',
				'default' => 0
			),
			'isDescendentOfQueryLoop' => array(
				'type' => 'boolean',
				'default' => false
			),
			'textAlign' => array(
				'type' => 'string',
				'default' => ''
			),
			'isDescendentOfSingleProductBlock' => array(
				'type' => 'boolean',
				'default' => false
			),
			'isDescendentOfSingleProductTemplate' => array(
				'type' => 'boolean',
				'default' => false
			)
		),
		'supports' => array(
			'interactivity' => array(
				'clientNavigation' => true
			),
			'color' => array(
				'text' => true,
				'background' => false,
				'link' => false,
				'__experimentalSkipSerialization' => true
			),
			'spacing' => array(
				'margin' => true,
				'padding' => true
			),
			'typography' => array(
				'fontSize' => true,
				'__experimentalSkipSerialization' => true
			),
			'__experimentalSelector' => '.spssp-block-components-product-rating'
		),
		'ancestor' => array(
			'smart-store-pro/all-products',
			'smart-store-pro/single-product',
			'smart-store-pro/product-template',
			'core/post-template'
		),
		'usesContext' => array(
			'query',
			'queryId',
			'postId'
		),
		'keywords' => array(
			'WooCommerce',
			'product',
			'rating'
		),
		'textdomain' => 'woo-product-slider-pro'
	),

	'product-short-description' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/product-short-description',
		'icon' => 'page',
		'title' => 'Product Summary',
		'description' => 'Display a short description about a product.',
		'category' => 'smart-store-pro-element',
		'attributes' => array(
			'productId' => array(
				'type' => 'number',
				'default' => 0
			),
			'isDescendentOfQueryLoop' => array(
				'type' => 'boolean',
				'default' => false
			),
			'isDescendentOfSingleProductTemplate' => array(
				'type' => 'boolean',
				'default' => false
			),
			'isDescendentOfSingleProductBlock' => array(
				'type' => 'boolean',
				'default' => false
			),
			'isDescendantOfAllProducts' => array(
				'type' => 'boolean',
				'default' => false
			),
			'showDescriptionIfEmpty' => array(
				'type' => 'boolean',
				'default' => false
			),
			'showLink' => array(
				'type' => 'boolean',
				'default' => false
			),
			'summaryLength' => array(
				'type' => 'number',
				'default' => 0
			),
			'linkText' => array(
				'type' => 'string',
				'default' => ''
			)
		),
		'supports' => array(
			'interactivity' => array(
				'clientNavigation' => true
			),
			'color' => array(
				'text' => true,
				'background' => true,
				'link' => true
			),
			'spacing' => array(
				'margin' => true,
				'padding' => true
			),
			'typography' => array(
				'fontSize' => true,
				'lineHeight' => true,
				'textAlign' => true,
				'__experimentalFontFamily' => true,
				'__experimentalFontWeight' => true,
				'__experimentalFontStyle' => true,
				'__experimentalTextTransform' => true,
				'__experimentalTextDecoration' => true,
				'__experimentalLetterSpacing' => true,
				'__experimentalDefaultControls' => array(
					'fontSize' => true
				)
			),
			'__experimentalSelector' => '.spssp-block-components-product-summary'
		),
		'ancestor' => array(
			'smart-store-pro/all-products',
			'smart-store-pro/featured-product',
			'smart-store-pro/single-product',
			'smart-store-pro/product-template',
			'core/post-template'
		),
		'usesContext' => array(
			'query',
			'queryId',
			'postId'
		),
		'keywords' => array(
			'WooCommerce',
			'product',
			'summary'
		),
		'textdomain' => 'woo-product-slider-pro'
	),

	'product-template' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/product-template',
		'title' => 'Product Template',
		'category' => 'smart-store-pro-showcase',
		'description' => 'Contains the block elements used to render a product.',
		'keywords' => array(
			'WooCommerce',
			'product',
			'template'
		),
		'textdomain' => 'woo-product-slider-pro',
		'usesContext' => array(
			'queryId',
			'query',
			'queryContext',
			'displayLayout',
			'templateSlug',
			'postId',
			'queryContextIncludes',
			'collection',
			'__privateProductCollectionPreviewState'
		),
		'supports' => array(
			'interactivity' => true,
			'inserter' => false,
			'reusable' => false,
			'html' => false,
			'align' => array(
				'wide',
				'full'
			),
			'anchor' => true,
			'color' => array(
				'gradients' => true,
				'link' => true,
				'__experimentalDefaultControls' => array(
					'background' => true,
					'text' => true
				)
			),
			'typography' => array(
				'fontSize' => true,
				'lineHeight' => true,
				'__experimentalFontFamily' => true,
				'__experimentalFontWeight' => true,
				'__experimentalFontStyle' => true,
				'__experimentalTextTransform' => true,
				'__experimentalTextDecoration' => true,
				'__experimentalLetterSpacing' => true,
				'__experimentalDefaultControls' => array(
					'fontSize' => true
				)
			),
			'layout' => array(
				'allowEditing' => false,
				'allowSwitching' => false,
				'allowInheriting' => false,
				'allowSizingOnChildren' => false,
				'allowVerticalAlignment' => false
			),
			'email' => true
		)
	),

	'product-title' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/product-title',
		'version' => '1.0.0',
		'title' => 'Product Title',
		'category' => 'smart-store-pro-element',
		'keywords' => array(
			'product',
			'title',
			'woocommerce'
		),
		'description' => 'Display the title of a product.',
		'textdomain' => 'woo-product-slider-pro',
		'usesContext' => array(
			'query',
			'queryId',
			'postId'
		),
		'supports' => array(
			'html' => false,
			'interactivity' => array(
				'clientNavigation' => false
			),
			'__experimentalSelector' => '.spssp-block-components-product-title'
		),
		'attributes' => array(
			'queryId' => array(
				'type' => 'string'
			),
			'headingLevel' => array(
				'type' => 'number',
				'default' => 2
			),
			'showProductLink' => array(
				'type' => 'boolean',
				'default' => true
			),
			'linkTarget' => array(
				'type' => 'string'
			),
			'productId' => array(
				'type' => 'number',
				'default' => 0
			),
			'align' => array(
				'type' => 'string'
			),
			'sectionHeadingHTMLTag' => array(
				'type' => 'string',
				'default' => 'h2'
			),
			'layoutOptions' => array(
				'type' => 'object',
				'default' => array(
					'titleLength' => 'full',
					'limitCount' => 20,
					'alignment' => 'left'
				)
			),
			'productTitleTypography' => array(
				'type'    => 'object',
				'default' => array(
					'googleFont' => array(
						'family'   => 'Default',
						'variants' => array('300', '400', '500', '600', '700', '800'),
					),
					'typography' => array(
						'family'     => '',
						'fontWeight' => '',
						'style'      => '',
						'transform'  => '',
						'decoration' => '',
					),
				),
			),
			'productTitleFontsize' => array(
				'type'    => 'object',
				'default' => array(
					'device' => array(
						'Desktop' => '',
						'Tablet'  => '',
						'Mobile'  => '',
					),
				),
			),

			'productTitleGlobalTypo' => array(
				'type'    => 'object',
				'default' => array(),
			),
			'productTitleLineHeight'  => array(
				'type'    => 'object',
				'default' => array(
					'device' => array(
						'Desktop' => '',
						'Tablet'  => '',
						'Mobile'  => '',
					),
				),
			),

			'productTitleColor' => array(
				'type'    => 'object',
				'default' => array(
					'color' => '',
					'hover' => '',
				),
			),
			'productTitleFontSpacing' => array(
				'type'    => 'object',
				'default' => array(
					'margin' => array(
						'top'    => '',
						'bottom' => '',
						'left'   => '',
						'right'  => '',
					),
				),

			),
			'productTitleWordSpacing' => array(
				'type'    => 'object',
				'default' => array(
					'margin' => array(
						'top'    => '',
						'bottom' => '',
						'left'   => '',
						'right'  => '',
					),
				),

			),
			'productTitleMargin' => array(
				'type'    => 'object',
				'default' => array(
					'margin' => array(
						'top'    => '',
						'bottom' => '',
						'left'   => '',
						'right'  => '',
					)
				)
			),
			'productTitlePadding' => array(
				'type'    => 'object',
				'default' => array(
					'padding' => array(
						'top'    => '',
						'bottom' => '',
						'left'   => '',
						'right'  => '',
					)
				)
			),

			'productUnderline' => array(
				'type'    => 'boolean',
				'default' => true
			),

			'productTitleState' => array(
				'type'    => 'string',
				'default' => 'normal'
			),
			'productTitleColorType' => array(
				'type'    => 'string',
				'default' => 'solid'
			),
			'productTitleColor' => array(
				'type'    => 'object',
				'default' => array(
					'color' => '#222222',
					'hover' => '#ff469e',
				)
			),
			'productTitleGradient' => array(
				'type'    => 'object',
				'default' => array(
					'normal' => '',
					'hover'  => '',
				),
			),

		)
	),

	'smart-button' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/smart-button',
		'title' => 'Smart Button',
		'category' => 'smart-store-pro-smart',
		'keywords' => array(
			'button',
			'link',
			'cta'
		),
		'description' => 'A customizable button block.',
		'textdomain' => 'woo-product-slider-pro',
		'supports' => array(
			'align' => array(
				'wide',
				'full'
			),
			'html' => false,
			'multiple' => true,
			'reusable' => true,
			'spacing' => array(
				'padding' => true,
				'margin' => true
			)
		)
	),

	'smart-heading' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/smart-heading',
		'title' => 'Smart Heading',
		'category' => 'smart-store-pro-smart',
		'keywords' => array(
			'heading',
			'title',
			'text'
		),
		'description' => 'A customizable heading block.',
		'textdomain' => 'woo-product-slider-pro',
		'supports' => array(
			'align' => array(
				'wide',
				'full'
			),
			'html' => false,
			'multiple' => true,
			'reusable' => true,
			'typography' => array(
				'fontSize' => true,
				'lineHeight' => true
			),
			'spacing' => array(
				'padding' => true,
				'margin' => true
			)
		)
	),

	'smart-paragraph' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/smart-paragraph',
		'title' => 'Smart Paragraph',
		'category' => 'smart-store-pro-smart',
		'keywords' => array(
			'paragraph',
			'text',
			'content'
		),
		'description' => 'A customizable paragraph block.',
		'textdomain' => 'woo-product-slider-pro',
		'supports' => array(
			'align' => array(
				'wide',
				'full'
			),
			'html' => false,
			'multiple' => true,
			'reusable' => true,
			'typography' => array(
				'fontSize' => true,
				'lineHeight' => true
			),
			'spacing' => array(
				'padding' => true,
				'margin' => true
			)
		)
	),

	'stock-status' => array(
		'$schema' => 'https://schemas.wp.org/trunk/block.json',
		'apiVersion' => 3,
		'name' => 'smart-store-pro/stock-status',
		'icon' => 'info',
		'title' => 'Product Stock Indicator',
		'description' => 'Let shoppers know when products are out of stock or on back order. This block is hidden when products are in stock.',
		'category' => 'smart-store-pro-element',
		'attributes' => array(
			'isDescendantOfAllProducts' => array(
				'type' => 'boolean',
				'default' => false
			)
		),
		'supports' => array(
			'html' => false,
			'interactivity' => true,
			'color' => array(
				'text' => true,
				'background' => true
			),
			'typography' => array(
				'fontSize' => true,
				'lineHeight' => true,
				'__experimentalFontWeight' => true,
				'__experimentalFontFamily' => true,
				'__experimentalFontStyle' => true,
				'__experimentalTextTransform' => true,
				'__experimentalTextDecoration' => true,
				'__experimentalLetterSpacing' => true
			),
			'spacing' => array(
				'margin' => true,
				'padding' => true
			)
		),
		'ancestor' => array(
			'smart-store-pro/all-products',
			'smart-store-pro/single-product',
			'smart-store-pro/product-template',
			'core/post-template'
		),
		'usesContext' => array(
			'query',
			'queryId',
			'postId'
		),
		'keywords' => array(
			'WooCommerce',
			'product',
			'stock'
		),
		'textdomain' => 'woo-product-slider-pro'
	)
);
